name: 自动构建并上传

on:
  push:
    branches: [ "main" ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install and Build
        run: |
          yarn
          yarn run build

      - name: Commit zhenun_docs
        run: |
          git checkout --orphan zhenxun_docs
          mv build ../
          rm -rf ./.github ./.gitignore ./*
          mv ../build/* ./
          git config --local user.email 'l1040186796@gmail.com'
          git config --local user.name 'AkashiCoin'
          git add .
          git commit -m ":book: chore(zhenxun_docs): 自动构建文档"

      - name: 
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: zhenxun_docs
          repository: HibiKier/zhenxun_bot
          force: true